[2022-08-09 21:01:14,453] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.processing_tasks.training_model_b manual__2022-08-09T21:01:09.159475+00:00 [queued]>
[2022-08-09 21:01:14,465] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.processing_tasks.training_model_b manual__2022-08-09T21:01:09.159475+00:00 [queued]>
[2022-08-09 21:01:14,466] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 21:01:14,467] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-09 21:01:14,469] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 21:01:14,480] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): processing_tasks.training_model_b> on 2022-08-09 21:01:09.159475+00:00
[2022-08-09 21:01:14,487] {standard_task_runner.py:52} INFO - Started process 14954 to run task
[2022-08-09 21:01:14,498] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'processing_tasks.training_model_b', 'manual__2022-08-09T21:01:09.159475+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpc57jk67y', '--error-file', '/tmp/tmprp6g9_1x']
[2022-08-09 21:01:14,500] {standard_task_runner.py:80} INFO - Job 99: Subtask processing_tasks.training_model_b
[2022-08-09 21:01:14,547] {task_command.py:369} INFO - Running <TaskInstance: xcom_dag.processing_tasks.training_model_b manual__2022-08-09T21:01:09.159475+00:00 [running]> on host 40fffbcee5cb
[2022-08-09 21:01:14,655] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=processing_tasks.training_model_b
AIRFLOW_CTX_EXECUTION_DATE=2022-08-09T21:01:09.159475+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-09T21:01:09.159475+00:00
[2022-08-09 21:01:14,657] {logging_mixin.py:115} INFO - model's accuracy: 0.8993040020729344
[2022-08-09 21:01:14,658] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/xcom_dag.py", line 19, in _training_model
    ti.excom_push(key='model_accuracy', value='accuracy')
AttributeError: 'TaskInstance' object has no attribute 'excom_push'
[2022-08-09 21:01:14,669] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=xcom_dag, task_id=processing_tasks.training_model_b, execution_date=20220809T210109, start_date=20220809T210114, end_date=20220809T210114
[2022-08-09 21:01:14,677] {standard_task_runner.py:97} ERROR - Failed to execute job 99 for task processing_tasks.training_model_b ('TaskInstance' object has no attribute 'excom_push'; 14954)
[2022-08-09 21:01:14,708] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-09 21:01:14,736] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
