[2022-08-09 21:00:45,467] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.processing_tasks.training_model_b manual__2022-08-09T21:00:41.338536+00:00 [queued]>
[2022-08-09 21:00:45,480] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.processing_tasks.training_model_b manual__2022-08-09T21:00:41.338536+00:00 [queued]>
[2022-08-09 21:00:45,484] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 21:00:45,485] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-09 21:00:45,486] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 21:00:45,495] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): processing_tasks.training_model_b> on 2022-08-09 21:00:41.338536+00:00
[2022-08-09 21:00:45,499] {standard_task_runner.py:52} INFO - Started process 14918 to run task
[2022-08-09 21:00:45,503] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'processing_tasks.training_model_b', 'manual__2022-08-09T21:00:41.338536+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpkg182ny0', '--error-file', '/tmp/tmpnayl4kxg']
[2022-08-09 21:00:45,504] {standard_task_runner.py:80} INFO - Job 94: Subtask processing_tasks.training_model_b
[2022-08-09 21:00:45,546] {task_command.py:369} INFO - Running <TaskInstance: xcom_dag.processing_tasks.training_model_b manual__2022-08-09T21:00:41.338536+00:00 [running]> on host 40fffbcee5cb
[2022-08-09 21:00:45,594] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=processing_tasks.training_model_b
AIRFLOW_CTX_EXECUTION_DATE=2022-08-09T21:00:41.338536+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-09T21:00:41.338536+00:00
[2022-08-09 21:00:45,596] {logging_mixin.py:115} INFO - model's accuracy: 4.539485023167416
[2022-08-09 21:00:45,597] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/xcom_dag.py", line 19, in _training_model
    ti.excom_push(key='model_accuracy', value='accuracy')
AttributeError: 'TaskInstance' object has no attribute 'excom_push'
[2022-08-09 21:00:45,606] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=xcom_dag, task_id=processing_tasks.training_model_b, execution_date=20220809T210041, start_date=20220809T210045, end_date=20220809T210045
[2022-08-09 21:00:45,614] {standard_task_runner.py:97} ERROR - Failed to execute job 94 for task processing_tasks.training_model_b ('TaskInstance' object has no attribute 'excom_push'; 14918)
[2022-08-09 21:00:45,635] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-09 21:00:45,672] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
