[2022-08-09 01:37:08,464] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:08,466] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:37:08,467] {logging_mixin.py:115} INFO - [2022-08-09 01:37:08,467] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:09,451] {logging_mixin.py:115} INFO - [2022-08-09 01:37:09,446] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:37:09,452] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:09,472] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 1.011 seconds
[2022-08-09 01:37:40,041] {processor.py:153} INFO - Started process (PID=98) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:40,044] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:37:40,048] {logging_mixin.py:115} INFO - [2022-08-09 01:37:40,047] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:40,301] {logging_mixin.py:115} INFO - [2022-08-09 01:37:40,299] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:37:40,302] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:40,313] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.274 seconds
[2022-08-09 01:38:10,758] {processor.py:153} INFO - Started process (PID=161) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:10,761] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:38:10,763] {logging_mixin.py:115} INFO - [2022-08-09 01:38:10,763] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:11,014] {logging_mixin.py:115} INFO - [2022-08-09 01:38:11,012] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:38:11,016] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:11,025] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.271 seconds
[2022-08-09 01:38:41,260] {processor.py:153} INFO - Started process (PID=224) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:41,261] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:38:41,262] {logging_mixin.py:115} INFO - [2022-08-09 01:38:41,262] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:41,479] {logging_mixin.py:115} INFO - [2022-08-09 01:38:41,477] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:38:41,480] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:41,492] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.235 seconds
[2022-08-09 01:39:11,779] {processor.py:153} INFO - Started process (PID=287) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:11,782] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:39:11,785] {logging_mixin.py:115} INFO - [2022-08-09 01:39:11,784] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:11,998] {logging_mixin.py:115} INFO - [2022-08-09 01:39:11,996] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:39:11,999] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:12,009] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.232 seconds
[2022-08-09 01:39:42,325] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:42,328] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:39:42,331] {logging_mixin.py:115} INFO - [2022-08-09 01:39:42,331] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:42,563] {logging_mixin.py:115} INFO - [2022-08-09 01:39:42,561] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:39:42,565] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:42,575] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.260 seconds
[2022-08-09 01:40:12,906] {processor.py:153} INFO - Started process (PID=404) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:12,911] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:40:12,912] {logging_mixin.py:115} INFO - [2022-08-09 01:40:12,912] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:13,130] {logging_mixin.py:115} INFO - [2022-08-09 01:40:13,129] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:40:13,131] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:13,142] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.241 seconds
[2022-08-09 01:40:43,435] {processor.py:153} INFO - Started process (PID=467) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:43,438] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:40:43,440] {logging_mixin.py:115} INFO - [2022-08-09 01:40:43,440] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:43,658] {logging_mixin.py:115} INFO - [2022-08-09 01:40:43,656] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:40:43,660] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:43,670] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.241 seconds
[2022-08-09 01:41:14,034] {processor.py:153} INFO - Started process (PID=530) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:14,038] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:41:14,042] {logging_mixin.py:115} INFO - [2022-08-09 01:41:14,042] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:14,258] {logging_mixin.py:115} INFO - [2022-08-09 01:41:14,256] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:41:14,259] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:14,270] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.241 seconds
[2022-08-09 01:41:44,553] {processor.py:153} INFO - Started process (PID=593) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:44,555] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:41:44,557] {logging_mixin.py:115} INFO - [2022-08-09 01:41:44,556] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:44,797] {logging_mixin.py:115} INFO - [2022-08-09 01:41:44,794] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:41:44,798] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:44,810] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.262 seconds
[2022-08-09 01:42:15,200] {processor.py:153} INFO - Started process (PID=656) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:15,203] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:42:15,205] {logging_mixin.py:115} INFO - [2022-08-09 01:42:15,205] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:15,425] {logging_mixin.py:115} INFO - [2022-08-09 01:42:15,423] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:42:15,427] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:15,438] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.244 seconds
[2022-08-09 01:42:46,022] {processor.py:153} INFO - Started process (PID=719) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:46,025] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:42:46,028] {logging_mixin.py:115} INFO - [2022-08-09 01:42:46,027] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:46,247] {logging_mixin.py:115} INFO - [2022-08-09 01:42:46,245] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:42:46,249] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:46,259] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.244 seconds
[2022-08-09 01:43:17,014] {processor.py:153} INFO - Started process (PID=783) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:17,015] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:43:17,016] {logging_mixin.py:115} INFO - [2022-08-09 01:43:17,016] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:17,234] {logging_mixin.py:115} INFO - [2022-08-09 01:43:17,232] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:43:17,235] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:17,246] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.235 seconds
[2022-08-09 01:43:47,956] {processor.py:153} INFO - Started process (PID=838) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:47,958] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:43:47,959] {logging_mixin.py:115} INFO - [2022-08-09 01:43:47,959] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:48,207] {logging_mixin.py:115} INFO - [2022-08-09 01:43:48,205] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:43:48,209] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:48,220] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.266 seconds
[2022-08-09 01:44:18,952] {processor.py:153} INFO - Started process (PID=901) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:18,954] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:44:18,957] {logging_mixin.py:115} INFO - [2022-08-09 01:44:18,956] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:19,172] {logging_mixin.py:115} INFO - [2022-08-09 01:44:19,170] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:44:19,173] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:19,184] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.240 seconds
[2022-08-09 01:44:49,978] {processor.py:153} INFO - Started process (PID=965) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:49,980] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:44:49,982] {logging_mixin.py:115} INFO - [2022-08-09 01:44:49,982] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:50,203] {logging_mixin.py:115} INFO - [2022-08-09 01:44:50,200] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:44:50,204] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:50,214] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.242 seconds
[2022-08-09 01:45:20,883] {processor.py:153} INFO - Started process (PID=1028) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:20,887] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:45:20,890] {logging_mixin.py:115} INFO - [2022-08-09 01:45:20,890] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:21,121] {logging_mixin.py:115} INFO - [2022-08-09 01:45:21,118] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:45:21,123] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:21,135] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.257 seconds
[2022-08-09 01:45:51,292] {processor.py:153} INFO - Started process (PID=1093) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:51,294] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:45:51,294] {logging_mixin.py:115} INFO - [2022-08-09 01:45:51,294] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:51,508] {logging_mixin.py:115} INFO - [2022-08-09 01:45:51,506] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:45:51,509] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:51,522] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.232 seconds
[2022-08-09 01:46:22,214] {processor.py:153} INFO - Started process (PID=1155) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:22,217] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:46:22,220] {logging_mixin.py:115} INFO - [2022-08-09 01:46:22,220] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:22,455] {logging_mixin.py:115} INFO - [2022-08-09 01:46:22,453] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:46:22,456] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:22,468] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.259 seconds
[2022-08-09 01:46:52,880] {processor.py:153} INFO - Started process (PID=1219) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:52,883] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:46:52,884] {logging_mixin.py:115} INFO - [2022-08-09 01:46:52,884] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:53,111] {logging_mixin.py:115} INFO - [2022-08-09 01:46:53,108] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:46:53,112] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:53,124] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.248 seconds
[2022-08-09 01:47:23,745] {processor.py:153} INFO - Started process (PID=1283) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:23,746] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:47:23,747] {logging_mixin.py:115} INFO - [2022-08-09 01:47:23,747] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:23,986] {logging_mixin.py:115} INFO - [2022-08-09 01:47:23,984] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:47:23,987] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:23,997] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.255 seconds
[2022-08-09 01:47:54,601] {processor.py:153} INFO - Started process (PID=1337) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:54,604] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:47:54,606] {logging_mixin.py:115} INFO - [2022-08-09 01:47:54,606] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:54,832] {logging_mixin.py:115} INFO - [2022-08-09 01:47:54,830] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:47:54,835] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:54,846] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.251 seconds
[2022-08-09 01:48:25,459] {processor.py:153} INFO - Started process (PID=1400) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:25,460] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:48:25,461] {logging_mixin.py:115} INFO - [2022-08-09 01:48:25,461] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:25,690] {logging_mixin.py:115} INFO - [2022-08-09 01:48:25,687] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:48:25,692] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:25,706] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.249 seconds
[2022-08-09 01:48:56,346] {processor.py:153} INFO - Started process (PID=1463) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:56,348] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:48:56,349] {logging_mixin.py:115} INFO - [2022-08-09 01:48:56,349] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:56,588] {logging_mixin.py:115} INFO - [2022-08-09 01:48:56,586] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:48:56,589] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:56,604] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.260 seconds
[2022-08-09 01:49:27,237] {processor.py:153} INFO - Started process (PID=1526) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:27,240] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:49:27,243] {logging_mixin.py:115} INFO - [2022-08-09 01:49:27,243] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:27,478] {logging_mixin.py:115} INFO - [2022-08-09 01:49:27,475] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:49:27,481] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:27,493] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.261 seconds
[2022-08-09 01:49:58,209] {processor.py:153} INFO - Started process (PID=1589) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:58,212] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:49:58,214] {logging_mixin.py:115} INFO - [2022-08-09 01:49:58,214] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:58,454] {logging_mixin.py:115} INFO - [2022-08-09 01:49:58,452] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:49:58,455] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:58,467] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.264 seconds
[2022-08-09 01:50:29,047] {processor.py:153} INFO - Started process (PID=1652) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:50:29,049] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:50:29,051] {logging_mixin.py:115} INFO - [2022-08-09 01:50:29,051] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:50:29,271] {logging_mixin.py:115} INFO - [2022-08-09 01:50:29,269] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:50:29,272] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:50:29,283] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.244 seconds
[2022-08-09 01:50:59,729] {processor.py:153} INFO - Started process (PID=1716) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:50:59,733] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:50:59,735] {logging_mixin.py:115} INFO - [2022-08-09 01:50:59,735] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:50:59,990] {logging_mixin.py:115} INFO - [2022-08-09 01:50:59,987] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:50:59,991] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:51:00,004] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.282 seconds
[2022-08-09 01:51:30,484] {processor.py:153} INFO - Started process (PID=1779) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:51:30,486] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:51:30,487] {logging_mixin.py:115} INFO - [2022-08-09 01:51:30,487] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:51:30,700] {logging_mixin.py:115} INFO - [2022-08-09 01:51:30,697] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:51:30,702] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:51:30,714] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.232 seconds
[2022-08-09 01:52:01,165] {processor.py:153} INFO - Started process (PID=1833) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:52:01,167] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:52:01,168] {logging_mixin.py:115} INFO - [2022-08-09 01:52:01,168] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:52:01,378] {logging_mixin.py:115} INFO - [2022-08-09 01:52:01,375] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:52:01,379] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:52:01,389] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.227 seconds
[2022-08-09 01:52:32,015] {processor.py:153} INFO - Started process (PID=1896) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:52:32,020] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:52:32,022] {logging_mixin.py:115} INFO - [2022-08-09 01:52:32,022] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:52:32,236] {logging_mixin.py:115} INFO - [2022-08-09 01:52:32,233] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:52:32,238] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:52:32,249] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.241 seconds
[2022-08-09 01:53:02,736] {processor.py:153} INFO - Started process (PID=1959) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:53:02,738] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:53:02,740] {logging_mixin.py:115} INFO - [2022-08-09 01:53:02,740] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:53:02,949] {logging_mixin.py:115} INFO - [2022-08-09 01:53:02,947] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:53:02,951] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:53:02,961] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.229 seconds
[2022-08-09 01:53:33,778] {processor.py:153} INFO - Started process (PID=2022) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:53:33,782] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:53:33,784] {logging_mixin.py:115} INFO - [2022-08-09 01:53:33,784] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:53:33,994] {logging_mixin.py:115} INFO - [2022-08-09 01:53:33,992] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:53:33,996] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:53:34,008] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.237 seconds
[2022-08-09 01:54:04,715] {processor.py:153} INFO - Started process (PID=2085) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:54:04,716] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:54:04,717] {logging_mixin.py:115} INFO - [2022-08-09 01:54:04,717] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:54:04,941] {logging_mixin.py:115} INFO - [2022-08-09 01:54:04,938] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:54:04,942] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:54:04,954] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.241 seconds
[2022-08-09 01:54:35,420] {processor.py:153} INFO - Started process (PID=2148) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:54:35,422] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:54:35,425] {logging_mixin.py:115} INFO - [2022-08-09 01:54:35,424] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:54:35,644] {logging_mixin.py:115} INFO - [2022-08-09 01:54:35,642] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:54:35,646] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:54:35,657] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.242 seconds
[2022-08-09 01:55:06,000] {processor.py:153} INFO - Started process (PID=2211) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:55:06,002] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:55:06,004] {logging_mixin.py:115} INFO - [2022-08-09 01:55:06,004] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:55:06,211] {logging_mixin.py:115} INFO - [2022-08-09 01:55:06,210] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:55:06,214] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:55:06,225] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.229 seconds
[2022-08-09 01:55:36,751] {processor.py:153} INFO - Started process (PID=2275) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:55:36,753] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:55:36,754] {logging_mixin.py:115} INFO - [2022-08-09 01:55:36,754] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:55:36,973] {logging_mixin.py:115} INFO - [2022-08-09 01:55:36,971] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:55:36,974] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:55:36,984] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.236 seconds
[2022-08-09 01:56:07,459] {processor.py:153} INFO - Started process (PID=2329) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:56:07,461] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:56:07,462] {logging_mixin.py:115} INFO - [2022-08-09 01:56:07,462] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:56:07,813] {logging_mixin.py:115} INFO - [2022-08-09 01:56:07,809] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:56:07,841] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:56:07,903] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.447 seconds
[2022-08-09 01:56:38,541] {processor.py:153} INFO - Started process (PID=2393) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:56:38,544] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:56:38,546] {logging_mixin.py:115} INFO - [2022-08-09 01:56:38,546] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:56:38,752] {logging_mixin.py:115} INFO - [2022-08-09 01:56:38,750] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:56:38,754] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:56:38,765] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.226 seconds
[2022-08-09 01:57:08,891] {processor.py:153} INFO - Started process (PID=2458) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:57:08,892] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:57:08,894] {logging_mixin.py:115} INFO - [2022-08-09 01:57:08,894] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:57:09,102] {logging_mixin.py:115} INFO - [2022-08-09 01:57:09,100] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:57:09,103] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:57:09,116] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.227 seconds
[2022-08-09 01:57:39,527] {processor.py:153} INFO - Started process (PID=2520) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:57:39,544] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:57:39,545] {logging_mixin.py:115} INFO - [2022-08-09 01:57:39,545] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:57:39,762] {logging_mixin.py:115} INFO - [2022-08-09 01:57:39,760] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:57:39,764] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:57:39,775] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.253 seconds
[2022-08-09 01:58:10,510] {processor.py:153} INFO - Started process (PID=2583) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:58:10,513] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:58:10,516] {logging_mixin.py:115} INFO - [2022-08-09 01:58:10,516] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:58:10,758] {logging_mixin.py:115} INFO - [2022-08-09 01:58:10,756] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:58:10,760] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:58:10,773] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.272 seconds
[2022-08-09 01:58:41,465] {processor.py:153} INFO - Started process (PID=2646) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:58:41,468] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:58:41,470] {logging_mixin.py:115} INFO - [2022-08-09 01:58:41,470] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:58:41,697] {logging_mixin.py:115} INFO - [2022-08-09 01:58:41,695] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:58:41,698] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:58:41,710] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.250 seconds
[2022-08-09 01:59:12,451] {processor.py:153} INFO - Started process (PID=2709) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:59:12,455] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:59:12,457] {logging_mixin.py:115} INFO - [2022-08-09 01:59:12,457] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:59:12,681] {logging_mixin.py:115} INFO - [2022-08-09 01:59:12,678] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:59:12,683] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:59:12,694] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.249 seconds
[2022-08-09 01:59:43,316] {processor.py:153} INFO - Started process (PID=2772) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:59:43,319] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:59:43,320] {logging_mixin.py:115} INFO - [2022-08-09 01:59:43,320] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:59:43,578] {logging_mixin.py:115} INFO - [2022-08-09 01:59:43,576] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:59:43,579] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:59:43,599] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.286 seconds
[2022-08-09 02:00:14,248] {processor.py:153} INFO - Started process (PID=2826) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:00:14,249] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:00:14,250] {logging_mixin.py:115} INFO - [2022-08-09 02:00:14,250] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:00:14,472] {logging_mixin.py:115} INFO - [2022-08-09 02:00:14,470] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:00:14,473] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:00:14,485] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.239 seconds
[2022-08-09 02:00:45,244] {processor.py:153} INFO - Started process (PID=2888) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:00:45,246] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:00:45,249] {logging_mixin.py:115} INFO - [2022-08-09 02:00:45,248] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:00:45,465] {logging_mixin.py:115} INFO - [2022-08-09 02:00:45,463] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:00:45,466] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:00:45,478] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.240 seconds
[2022-08-09 02:01:16,087] {processor.py:153} INFO - Started process (PID=2952) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:01:16,090] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:01:16,093] {logging_mixin.py:115} INFO - [2022-08-09 02:01:16,093] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:01:16,324] {logging_mixin.py:115} INFO - [2022-08-09 02:01:16,322] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:01:16,325] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:01:16,339] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.258 seconds
[2022-08-09 02:01:47,029] {processor.py:153} INFO - Started process (PID=3015) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:01:47,032] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:01:47,034] {logging_mixin.py:115} INFO - [2022-08-09 02:01:47,034] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:01:47,243] {logging_mixin.py:115} INFO - [2022-08-09 02:01:47,241] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:01:47,245] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:01:47,258] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.234 seconds
[2022-08-09 02:02:17,832] {processor.py:153} INFO - Started process (PID=3078) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:02:17,835] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:02:17,837] {logging_mixin.py:115} INFO - [2022-08-09 02:02:17,837] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:02:18,043] {logging_mixin.py:115} INFO - [2022-08-09 02:02:18,041] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:02:18,045] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:02:18,056] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.228 seconds
[2022-08-09 02:02:48,650] {processor.py:153} INFO - Started process (PID=3140) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:02:48,651] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:02:48,653] {logging_mixin.py:115} INFO - [2022-08-09 02:02:48,653] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:02:48,859] {logging_mixin.py:115} INFO - [2022-08-09 02:02:48,857] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:02:48,860] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:02:48,871] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.225 seconds
[2022-08-09 02:03:19,508] {processor.py:153} INFO - Started process (PID=3203) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:03:19,511] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:03:19,513] {logging_mixin.py:115} INFO - [2022-08-09 02:03:19,513] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:03:19,773] {logging_mixin.py:115} INFO - [2022-08-09 02:03:19,770] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:03:19,774] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:03:19,786] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.284 seconds
[2022-08-09 02:03:50,275] {processor.py:153} INFO - Started process (PID=3266) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:03:50,276] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:03:50,278] {logging_mixin.py:115} INFO - [2022-08-09 02:03:50,278] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:03:50,483] {logging_mixin.py:115} INFO - [2022-08-09 02:03:50,481] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:03:50,484] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:03:50,496] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.225 seconds
[2022-08-09 02:04:21,095] {processor.py:153} INFO - Started process (PID=3327) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:04:21,098] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:04:21,099] {logging_mixin.py:115} INFO - [2022-08-09 02:04:21,099] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:04:21,355] {logging_mixin.py:115} INFO - [2022-08-09 02:04:21,352] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:04:21,357] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:04:21,372] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.279 seconds
[2022-08-09 02:04:51,977] {processor.py:153} INFO - Started process (PID=3383) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:04:51,979] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:04:51,980] {logging_mixin.py:115} INFO - [2022-08-09 02:04:51,980] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:04:52,186] {logging_mixin.py:115} INFO - [2022-08-09 02:04:52,183] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:04:52,188] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:04:52,201] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.226 seconds
[2022-08-09 02:05:02,734] {processor.py:153} INFO - Started process (PID=3426) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:05:02,735] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:05:02,736] {logging_mixin.py:115} INFO - [2022-08-09 02:05:02,736] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:05:02,922] {logging_mixin.py:115} INFO - [2022-08-09 02:05:02,920] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 53, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:05:02,924] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:05:02,935] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.202 seconds
[2022-08-09 02:05:33,122] {processor.py:153} INFO - Started process (PID=3489) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:05:33,126] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:05:33,127] {logging_mixin.py:115} INFO - [2022-08-09 02:05:33,127] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:05:33,337] {logging_mixin.py:115} INFO - [2022-08-09 02:05:33,335] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 53, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:05:33,338] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:05:33,348] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.230 seconds
[2022-08-09 02:06:03,912] {processor.py:153} INFO - Started process (PID=3551) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:06:03,914] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:06:03,916] {logging_mixin.py:115} INFO - [2022-08-09 02:06:03,916] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:06:04,104] {logging_mixin.py:115} INFO - [2022-08-09 02:06:04,101] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 53, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:06:04,106] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:06:04,117] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.208 seconds
[2022-08-09 02:06:19,056] {processor.py:153} INFO - Started process (PID=3569) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:06:19,057] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:06:19,058] {logging_mixin.py:115} INFO - [2022-08-09 02:06:19,058] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:06:19,253] {logging_mixin.py:115} INFO - [2022-08-09 02:06:19,251] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 57, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:06:19,254] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:06:19,265] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.211 seconds
[2022-08-09 02:06:49,813] {processor.py:153} INFO - Started process (PID=3625) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:06:49,814] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:06:49,815] {logging_mixin.py:115} INFO - [2022-08-09 02:06:49,815] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:06:49,987] {logging_mixin.py:115} INFO - [2022-08-09 02:06:49,985] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 57, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:06:49,989] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:06:50,000] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.189 seconds
[2022-08-09 02:07:20,730] {processor.py:153} INFO - Started process (PID=3688) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:07:20,734] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:07:20,737] {logging_mixin.py:115} INFO - [2022-08-09 02:07:20,737] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:07:20,881] {logging_mixin.py:115} INFO - [2022-08-09 02:07:20,879] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 57, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:07:20,882] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:07:20,894] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.171 seconds
[2022-08-09 02:07:51,249] {processor.py:153} INFO - Started process (PID=3749) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:07:51,251] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:07:51,253] {logging_mixin.py:115} INFO - [2022-08-09 02:07:51,253] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:07:51,383] {logging_mixin.py:115} INFO - [2022-08-09 02:07:51,380] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 57, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:07:51,384] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:07:51,397] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.152 seconds
[2022-08-09 02:07:56,765] {processor.py:153} INFO - Started process (PID=3770) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:07:56,767] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:07:56,770] {logging_mixin.py:115} INFO - [2022-08-09 02:07:56,770] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:07:56,945] {logging_mixin.py:115} INFO - [2022-08-09 02:07:56,942] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 59, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:07:56,946] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:07:56,957] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.201 seconds
[2022-08-09 02:08:27,302] {processor.py:153} INFO - Started process (PID=3824) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:08:27,304] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:08:27,307] {logging_mixin.py:115} INFO - [2022-08-09 02:08:27,307] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:08:27,524] {logging_mixin.py:115} INFO - [2022-08-09 02:08:27,521] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 59, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:08:27,525] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:08:27,540] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.244 seconds
[2022-08-09 02:08:44,427] {processor.py:153} INFO - Started process (PID=3868) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:08:44,430] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:08:44,431] {logging_mixin.py:115} INFO - [2022-08-09 02:08:44,431] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:08:44,574] {logging_mixin.py:115} INFO - [2022-08-09 02:08:44,572] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 60, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:08:44,576] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:08:44,589] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.167 seconds
[2022-08-09 02:09:14,919] {processor.py:153} INFO - Started process (PID=3930) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:09:14,921] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:09:14,923] {logging_mixin.py:115} INFO - [2022-08-09 02:09:14,923] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:09:15,073] {logging_mixin.py:115} INFO - [2022-08-09 02:09:15,071] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 60, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:09:15,074] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:09:15,089] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.174 seconds
[2022-08-09 02:09:45,399] {processor.py:153} INFO - Started process (PID=3992) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:09:45,404] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:09:45,407] {logging_mixin.py:115} INFO - [2022-08-09 02:09:45,407] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:09:45,545] {logging_mixin.py:115} INFO - [2022-08-09 02:09:45,542] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 60, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:09:45,546] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:09:45,558] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.164 seconds
[2022-08-09 02:09:55,477] {processor.py:153} INFO - Started process (PID=4002) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:09:55,479] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:09:55,481] {logging_mixin.py:115} INFO - [2022-08-09 02:09:55,481] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:09:55,630] {logging_mixin.py:115} INFO - [2022-08-09 02:09:55,628] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 60, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:09:55,631] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:09:55,643] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.171 seconds
[2022-08-09 02:10:26,081] {processor.py:153} INFO - Started process (PID=4057) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:10:26,084] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:10:26,086] {logging_mixin.py:115} INFO - [2022-08-09 02:10:26,085] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:10:26,218] {logging_mixin.py:115} INFO - [2022-08-09 02:10:26,216] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 60, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:10:26,219] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:10:26,236] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.160 seconds
[2022-08-09 02:10:56,513] {processor.py:153} INFO - Started process (PID=4120) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:10:56,516] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:10:56,518] {logging_mixin.py:115} INFO - [2022-08-09 02:10:56,518] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:10:56,642] {logging_mixin.py:115} INFO - [2022-08-09 02:10:56,640] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 60, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:10:56,644] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:10:56,656] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.147 seconds
[2022-08-09 02:11:05,922] {processor.py:153} INFO - Started process (PID=4165) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:11:05,924] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:11:05,926] {logging_mixin.py:115} INFO - [2022-08-09 02:11:05,926] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:11:06,065] {logging_mixin.py:115} INFO - [2022-08-09 02:11:06,062] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:11:06,067] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:11:06,079] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.162 seconds
[2022-08-09 02:11:36,544] {processor.py:153} INFO - Started process (PID=4229) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:11:36,545] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:11:36,546] {logging_mixin.py:115} INFO - [2022-08-09 02:11:36,546] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:11:36,679] {logging_mixin.py:115} INFO - [2022-08-09 02:11:36,676] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:11:36,680] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:11:36,692] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.152 seconds
[2022-08-09 02:12:03,520] {processor.py:153} INFO - Started process (PID=4270) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:12:03,524] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:12:03,528] {logging_mixin.py:115} INFO - [2022-08-09 02:12:03,528] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:12:03,742] {logging_mixin.py:115} INFO - [2022-08-09 02:12:03,739] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:12:03,745] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:12:03,759] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.246 seconds
[2022-08-09 02:12:34,192] {processor.py:153} INFO - Started process (PID=4331) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:12:34,194] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:12:34,196] {logging_mixin.py:115} INFO - [2022-08-09 02:12:34,196] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:12:34,326] {logging_mixin.py:115} INFO - [2022-08-09 02:12:34,324] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:12:34,329] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:12:34,341] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.153 seconds
[2022-08-09 02:13:04,964] {processor.py:153} INFO - Started process (PID=4394) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:04,968] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:13:04,971] {logging_mixin.py:115} INFO - [2022-08-09 02:13:04,971] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:05,152] {logging_mixin.py:115} INFO - [2022-08-09 02:13:05,150] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:13:05,154] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:05,168] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.210 seconds
[2022-08-09 02:13:35,511] {processor.py:153} INFO - Started process (PID=4457) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:35,516] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:13:35,519] {logging_mixin.py:115} INFO - [2022-08-09 02:13:35,519] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:35,676] {logging_mixin.py:115} INFO - [2022-08-09 02:13:35,670] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:13:35,677] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:35,694] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.188 seconds
[2022-08-09 02:13:43,118] {processor.py:153} INFO - Started process (PID=4481) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:43,120] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:13:43,121] {logging_mixin.py:115} INFO - [2022-08-09 02:13:43,121] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:43,267] {logging_mixin.py:115} INFO - [2022-08-09 02:13:43,264] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:13:43,268] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:43,281] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.165 seconds
[2022-08-09 02:13:50,350] {processor.py:153} INFO - Started process (PID=4483) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:50,351] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:13:50,353] {logging_mixin.py:115} INFO - [2022-08-09 02:13:50,353] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:50,493] {logging_mixin.py:115} INFO - [2022-08-09 02:13:50,490] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:13:50,494] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:13:50,507] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.162 seconds
[2022-08-09 02:14:21,102] {processor.py:153} INFO - Started process (PID=4545) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:14:21,105] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:14:21,108] {logging_mixin.py:115} INFO - [2022-08-09 02:14:21,107] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:14:21,249] {logging_mixin.py:115} INFO - [2022-08-09 02:14:21,246] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:14:21,251] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:14:21,262] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.165 seconds
[2022-08-09 02:14:51,531] {processor.py:153} INFO - Started process (PID=4609) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:14:51,534] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:14:51,536] {logging_mixin.py:115} INFO - [2022-08-09 02:14:51,536] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:14:51,666] {logging_mixin.py:115} INFO - [2022-08-09 02:14:51,664] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:14:51,668] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:14:51,681] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.156 seconds
[2022-08-09 02:15:21,992] {processor.py:153} INFO - Started process (PID=4672) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:15:21,996] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:15:21,997] {logging_mixin.py:115} INFO - [2022-08-09 02:15:21,997] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:15:22,143] {logging_mixin.py:115} INFO - [2022-08-09 02:15:22,139] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 61, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 02:15:22,144] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:15:22,194] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.206 seconds
[2022-08-09 02:15:24,011] {processor.py:153} INFO - Started process (PID=4674) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:15:24,012] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:15:24,013] {logging_mixin.py:115} INFO - [2022-08-09 02:15:24,013] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:15:24,176] {logging_mixin.py:115} INFO - [2022-08-09 02:15:24,173] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:15:24,178] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:15:24,191] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.184 seconds
[2022-08-09 02:15:54,537] {processor.py:153} INFO - Started process (PID=4737) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:15:54,539] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:15:54,542] {logging_mixin.py:115} INFO - [2022-08-09 02:15:54,542] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:15:54,687] {logging_mixin.py:115} INFO - [2022-08-09 02:15:54,684] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:15:54,688] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:15:54,701] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.169 seconds
[2022-08-09 02:16:22,954] {processor.py:153} INFO - Started process (PID=4791) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:16:22,956] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:16:22,959] {logging_mixin.py:115} INFO - [2022-08-09 02:16:22,958] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:16:23,127] {logging_mixin.py:115} INFO - [2022-08-09 02:16:23,125] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:16:23,130] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:16:23,142] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.191 seconds
[2022-08-09 02:16:53,452] {processor.py:153} INFO - Started process (PID=4856) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:16:53,454] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:16:53,456] {logging_mixin.py:115} INFO - [2022-08-09 02:16:53,456] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:16:53,589] {logging_mixin.py:115} INFO - [2022-08-09 02:16:53,586] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:16:53,590] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:16:53,605] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.158 seconds
[2022-08-09 02:17:23,895] {processor.py:153} INFO - Started process (PID=4919) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:17:23,898] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:17:23,901] {logging_mixin.py:115} INFO - [2022-08-09 02:17:23,901] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:17:24,035] {logging_mixin.py:115} INFO - [2022-08-09 02:17:24,033] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:17:24,037] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:17:24,050] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.160 seconds
[2022-08-09 02:17:54,292] {processor.py:153} INFO - Started process (PID=4982) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:17:54,296] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:17:54,297] {logging_mixin.py:115} INFO - [2022-08-09 02:17:54,297] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:17:54,431] {logging_mixin.py:115} INFO - [2022-08-09 02:17:54,429] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:17:54,433] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:17:54,445] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.158 seconds
[2022-08-09 02:18:24,718] {processor.py:153} INFO - Started process (PID=5045) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:18:24,722] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:18:24,723] {logging_mixin.py:115} INFO - [2022-08-09 02:18:24,723] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:18:24,863] {logging_mixin.py:115} INFO - [2022-08-09 02:18:24,860] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:18:24,864] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:18:24,876] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.164 seconds
[2022-08-09 02:18:55,070] {processor.py:153} INFO - Started process (PID=5108) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:18:55,072] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:18:55,072] {logging_mixin.py:115} INFO - [2022-08-09 02:18:55,072] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:18:55,195] {logging_mixin.py:115} INFO - [2022-08-09 02:18:55,193] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:18:55,197] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:18:55,209] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.141 seconds
[2022-08-09 02:19:25,589] {processor.py:153} INFO - Started process (PID=5162) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:19:25,592] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:19:25,596] {logging_mixin.py:115} INFO - [2022-08-09 02:19:25,595] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:19:25,721] {logging_mixin.py:115} INFO - [2022-08-09 02:19:25,718] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:19:25,722] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:19:25,735] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.150 seconds
[2022-08-09 02:19:56,080] {processor.py:153} INFO - Started process (PID=5225) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:19:56,084] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:19:56,087] {logging_mixin.py:115} INFO - [2022-08-09 02:19:56,087] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:19:56,233] {logging_mixin.py:115} INFO - [2022-08-09 02:19:56,230] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:19:56,234] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:19:56,246] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.171 seconds
[2022-08-09 02:20:11,941] {processor.py:153} INFO - Started process (PID=5265) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:20:11,944] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:20:11,947] {logging_mixin.py:115} INFO - [2022-08-09 02:20:11,946] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:20:12,101] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:20:12,133] {logging_mixin.py:115} INFO - [2022-08-09 02:20:12,132] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:20:12,144] {logging_mixin.py:115} INFO - [2022-08-09 02:20:12,144] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:20:12,168] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.231 seconds
[2022-08-09 02:20:35,658] {processor.py:153} INFO - Started process (PID=5298) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:20:35,660] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:20:35,661] {logging_mixin.py:115} INFO - [2022-08-09 02:20:35,661] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:20:35,672] {logging_mixin.py:115} INFO - [2022-08-09 02:20:35,671] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 15
    METH(ti for "task instance")
                               ^
SyntaxError: invalid syntax
[2022-08-09 02:20:35,673] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:20:35,693] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.038 seconds
[2022-08-09 02:20:46,204] {processor.py:153} INFO - Started process (PID=5342) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:20:46,207] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:20:46,208] {logging_mixin.py:115} INFO - [2022-08-09 02:20:46,208] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:20:46,346] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:20:46,361] {logging_mixin.py:115} INFO - [2022-08-09 02:20:46,361] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:20:46,373] {logging_mixin.py:115} INFO - [2022-08-09 02:20:46,373] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:20:46,381] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.182 seconds
[2022-08-09 02:21:14,148] {processor.py:153} INFO - Started process (PID=5392) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:14,150] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:21:14,152] {logging_mixin.py:115} INFO - [2022-08-09 02:21:14,152] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:14,346] {logging_mixin.py:115} INFO - [2022-08-09 02:21:14,343] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 57, in <module>
    Sensor
NameError: name 'Sensor' is not defined
[2022-08-09 02:21:14,354] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:14,373] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.228 seconds
[2022-08-09 02:21:20,797] {processor.py:153} INFO - Started process (PID=5407) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:20,800] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:21:20,805] {logging_mixin.py:115} INFO - [2022-08-09 02:21:20,805] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:20,965] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:20,981] {logging_mixin.py:115} INFO - [2022-08-09 02:21:20,981] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:21:20,993] {logging_mixin.py:115} INFO - [2022-08-09 02:21:20,993] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:21:21,001] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.208 seconds
[2022-08-09 02:21:28,051] {processor.py:153} INFO - Started process (PID=5417) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:28,052] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:21:28,053] {logging_mixin.py:115} INFO - [2022-08-09 02:21:28,053] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:28,194] {logging_mixin.py:115} INFO - [2022-08-09 02:21:28,192] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 57, in <module>
    Sensor
NameError: name 'Sensor' is not defined
[2022-08-09 02:21:28,195] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:28,208] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.159 seconds
[2022-08-09 02:21:58,612] {processor.py:153} INFO - Started process (PID=5480) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:58,616] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:21:58,618] {logging_mixin.py:115} INFO - [2022-08-09 02:21:58,618] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:58,766] {logging_mixin.py:115} INFO - [2022-08-09 02:21:58,764] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 57, in <module>
    Sensor
NameError: name 'Sensor' is not defined
[2022-08-09 02:21:58,767] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:21:58,780] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.173 seconds
[2022-08-09 02:22:29,069] {processor.py:153} INFO - Started process (PID=5535) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:22:29,071] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:22:29,072] {logging_mixin.py:115} INFO - [2022-08-09 02:22:29,072] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:22:29,204] {logging_mixin.py:115} INFO - [2022-08-09 02:22:29,202] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 57, in <module>
    Sensor
NameError: name 'Sensor' is not defined
[2022-08-09 02:22:29,205] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:22:29,217] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.151 seconds
[2022-08-09 02:22:53,552] {processor.py:153} INFO - Started process (PID=5598) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:22:53,555] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:22:53,556] {logging_mixin.py:115} INFO - [2022-08-09 02:22:53,556] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:22:53,701] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:22:53,742] {logging_mixin.py:115} INFO - [2022-08-09 02:22:53,741] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:22:53,754] {logging_mixin.py:115} INFO - [2022-08-09 02:22:53,753] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:22:53,764] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.213 seconds
[2022-08-09 02:23:05,864] {processor.py:153} INFO - Started process (PID=5610) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:23:05,866] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:23:05,868] {logging_mixin.py:115} INFO - [2022-08-09 02:23:05,868] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:23:06,015] {logging_mixin.py:115} INFO - [2022-08-09 02:23:06,012] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:23:06,048] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:23:06,061] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.202 seconds
[2022-08-09 02:23:36,332] {processor.py:153} INFO - Started process (PID=5673) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:23:36,335] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:23:36,339] {logging_mixin.py:115} INFO - [2022-08-09 02:23:36,338] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:23:36,489] {logging_mixin.py:115} INFO - [2022-08-09 02:23:36,486] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:23:36,491] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:23:36,503] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.176 seconds
[2022-08-09 02:24:06,824] {processor.py:153} INFO - Started process (PID=5737) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:24:06,826] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:24:06,827] {logging_mixin.py:115} INFO - [2022-08-09 02:24:06,827] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:24:06,965] {logging_mixin.py:115} INFO - [2022-08-09 02:24:06,962] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:24:06,967] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:24:06,979] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.158 seconds
[2022-08-09 02:24:37,395] {processor.py:153} INFO - Started process (PID=5790) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:24:37,398] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:24:37,400] {logging_mixin.py:115} INFO - [2022-08-09 02:24:37,400] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:24:37,534] {logging_mixin.py:115} INFO - [2022-08-09 02:24:37,532] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 71, in <module>
    log_response=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 744, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: extract_user). Invalid arguments were:
**kwargs: {'http_con_id': 'user_api'}
[2022-08-09 02:24:37,535] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:24:37,550] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.162 seconds
[2022-08-09 02:24:49,480] {processor.py:153} INFO - Started process (PID=5826) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:24:49,482] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:24:49,485] {logging_mixin.py:115} INFO - [2022-08-09 02:24:49,485] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:24:49,641] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:24:49,700] {logging_mixin.py:115} INFO - [2022-08-09 02:24:49,700] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:24:49,718] {logging_mixin.py:115} INFO - [2022-08-09 02:24:49,718] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:24:49,732] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.257 seconds
[2022-08-09 02:25:12,094] {processor.py:153} INFO - Started process (PID=5864) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:25:12,095] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:25:12,096] {logging_mixin.py:115} INFO - [2022-08-09 02:25:12,096] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:25:12,218] {logging_mixin.py:115} INFO - [2022-08-09 02:25:12,216] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 77, in <module>
    python_callable=_process_user
NameError: name '_process_user' is not defined
[2022-08-09 02:25:12,221] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:25:12,233] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.141 seconds
[2022-08-09 02:25:35,717] {processor.py:153} INFO - Started process (PID=5918) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:25:35,718] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:25:35,719] {logging_mixin.py:115} INFO - [2022-08-09 02:25:35,719] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:25:35,860] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:25:35,902] {logging_mixin.py:115} INFO - [2022-08-09 02:25:35,901] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:25:35,917] {logging_mixin.py:115} INFO - [2022-08-09 02:25:35,917] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:25:35,927] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.212 seconds
[2022-08-09 02:25:55,024] {processor.py:153} INFO - Started process (PID=5972) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:25:55,025] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:25:55,026] {logging_mixin.py:115} INFO - [2022-08-09 02:25:55,026] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:25:55,196] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:25:55,207] {logging_mixin.py:115} INFO - [2022-08-09 02:25:55,207] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:25:55,218] {logging_mixin.py:115} INFO - [2022-08-09 02:25:55,218] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:25:55,226] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.204 seconds
[2022-08-09 02:26:23,537] {processor.py:153} INFO - Started process (PID=6027) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:26:23,540] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:26:23,542] {logging_mixin.py:115} INFO - [2022-08-09 02:26:23,542] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:26:23,698] {logging_mixin.py:115} INFO - [2022-08-09 02:26:23,696] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 83, in <module>
    python_callable=_store_user
NameError: name '_store_user' is not defined
[2022-08-09 02:26:23,699] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:26:23,711] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.180 seconds
[2022-08-09 02:26:39,644] {processor.py:153} INFO - Started process (PID=6047) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:26:39,646] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:26:39,648] {logging_mixin.py:115} INFO - [2022-08-09 02:26:39,648] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:26:39,812] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:26:39,855] {logging_mixin.py:115} INFO - [2022-08-09 02:26:39,855] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:26:39,866] {logging_mixin.py:115} INFO - [2022-08-09 02:26:39,866] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:26:39,876] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.235 seconds
[2022-08-09 02:27:00,286] {processor.py:153} INFO - Started process (PID=6100) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:27:00,287] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:27:00,288] {logging_mixin.py:115} INFO - [2022-08-09 02:27:00,288] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:27:00,419] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:27:00,429] {logging_mixin.py:115} INFO - [2022-08-09 02:27:00,428] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:27:00,441] {logging_mixin.py:115} INFO - [2022-08-09 02:27:00,441] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:27:00,450] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.166 seconds
[2022-08-09 02:27:11,374] {processor.py:153} INFO - Started process (PID=6110) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:27:11,375] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:27:11,376] {logging_mixin.py:115} INFO - [2022-08-09 02:27:11,376] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:27:11,509] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:27:11,549] {logging_mixin.py:115} INFO - [2022-08-09 02:27:11,548] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:27:11,560] {logging_mixin.py:115} INFO - [2022-08-09 02:27:11,560] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:27:11,569] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.199 seconds
[2022-08-09 02:27:42,108] {processor.py:153} INFO - Started process (PID=6164) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:27:42,110] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:27:42,112] {logging_mixin.py:115} INFO - [2022-08-09 02:27:42,112] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:27:42,242] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:27:42,262] {logging_mixin.py:115} INFO - [2022-08-09 02:27:42,262] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:27:42,272] {logging_mixin.py:115} INFO - [2022-08-09 02:27:42,272] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:27:42,278] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.177 seconds
[2022-08-09 02:28:12,668] {processor.py:153} INFO - Started process (PID=6226) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:28:12,671] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:28:12,672] {logging_mixin.py:115} INFO - [2022-08-09 02:28:12,672] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:28:12,786] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:28:12,808] {logging_mixin.py:115} INFO - [2022-08-09 02:28:12,808] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:28:12,819] {logging_mixin.py:115} INFO - [2022-08-09 02:28:12,819] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:28:12,825] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.160 seconds
[2022-08-09 02:28:43,160] {processor.py:153} INFO - Started process (PID=6289) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:28:43,163] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:28:43,165] {logging_mixin.py:115} INFO - [2022-08-09 02:28:43,165] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:28:43,291] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:28:43,312] {logging_mixin.py:115} INFO - [2022-08-09 02:28:43,312] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:28:43,323] {logging_mixin.py:115} INFO - [2022-08-09 02:28:43,323] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:28:43,329] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.174 seconds
[2022-08-09 02:29:13,570] {processor.py:153} INFO - Started process (PID=6352) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:29:13,571] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:29:13,572] {logging_mixin.py:115} INFO - [2022-08-09 02:29:13,572] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:29:13,684] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:29:13,706] {logging_mixin.py:115} INFO - [2022-08-09 02:29:13,706] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:29:13,717] {logging_mixin.py:115} INFO - [2022-08-09 02:29:13,717] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:29:13,724] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.156 seconds
[2022-08-09 02:29:43,984] {processor.py:153} INFO - Started process (PID=6415) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:29:43,987] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:29:43,989] {logging_mixin.py:115} INFO - [2022-08-09 02:29:43,989] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:29:44,116] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:29:44,138] {logging_mixin.py:115} INFO - [2022-08-09 02:29:44,137] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:29:44,149] {logging_mixin.py:115} INFO - [2022-08-09 02:29:44,149] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:29:44,154] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.176 seconds
[2022-08-09 02:30:14,468] {processor.py:153} INFO - Started process (PID=6477) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:30:14,472] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:30:14,476] {logging_mixin.py:115} INFO - [2022-08-09 02:30:14,476] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:30:14,604] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:30:14,626] {logging_mixin.py:115} INFO - [2022-08-09 02:30:14,626] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:30:14,637] {logging_mixin.py:115} INFO - [2022-08-09 02:30:14,637] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:30:14,643] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.180 seconds
[2022-08-09 02:30:44,909] {processor.py:153} INFO - Started process (PID=6531) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 02:30:44,912] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 02:30:44,914] {logging_mixin.py:115} INFO - [2022-08-09 02:30:44,914] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 02:30:45,045] {processor.py:651} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 02:30:45,067] {logging_mixin.py:115} INFO - [2022-08-09 02:30:45,066] {dag.py:2371} INFO - Sync 1 DAGs
[2022-08-09 02:30:45,077] {logging_mixin.py:115} INFO - [2022-08-09 02:30:45,077] {dag.py:2919} INFO - Setting next_dagrun for user_processing to 2022-08-08T00:00:00+00:00, run_after=2022-08-09T00:00:00+00:00
[2022-08-09 02:30:45,083] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.178 seconds
