[2022-08-09 01:37:08,464] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:08,466] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:37:08,467] {logging_mixin.py:115} INFO - [2022-08-09 01:37:08,467] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:09,451] {logging_mixin.py:115} INFO - [2022-08-09 01:37:09,446] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:37:09,452] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:09,472] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 1.011 seconds
[2022-08-09 01:37:40,041] {processor.py:153} INFO - Started process (PID=98) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:40,044] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:37:40,048] {logging_mixin.py:115} INFO - [2022-08-09 01:37:40,047] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:40,301] {logging_mixin.py:115} INFO - [2022-08-09 01:37:40,299] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:37:40,302] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:37:40,313] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.274 seconds
[2022-08-09 01:38:10,758] {processor.py:153} INFO - Started process (PID=161) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:10,761] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:38:10,763] {logging_mixin.py:115} INFO - [2022-08-09 01:38:10,763] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:11,014] {logging_mixin.py:115} INFO - [2022-08-09 01:38:11,012] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:38:11,016] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:11,025] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.271 seconds
[2022-08-09 01:38:41,260] {processor.py:153} INFO - Started process (PID=224) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:41,261] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:38:41,262] {logging_mixin.py:115} INFO - [2022-08-09 01:38:41,262] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:41,479] {logging_mixin.py:115} INFO - [2022-08-09 01:38:41,477] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:38:41,480] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:38:41,492] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.235 seconds
[2022-08-09 01:39:11,779] {processor.py:153} INFO - Started process (PID=287) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:11,782] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:39:11,785] {logging_mixin.py:115} INFO - [2022-08-09 01:39:11,784] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:11,998] {logging_mixin.py:115} INFO - [2022-08-09 01:39:11,996] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:39:11,999] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:12,009] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.232 seconds
[2022-08-09 01:39:42,325] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:42,328] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:39:42,331] {logging_mixin.py:115} INFO - [2022-08-09 01:39:42,331] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:42,563] {logging_mixin.py:115} INFO - [2022-08-09 01:39:42,561] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:39:42,565] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:39:42,575] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.260 seconds
[2022-08-09 01:40:12,906] {processor.py:153} INFO - Started process (PID=404) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:12,911] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:40:12,912] {logging_mixin.py:115} INFO - [2022-08-09 01:40:12,912] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:13,130] {logging_mixin.py:115} INFO - [2022-08-09 01:40:13,129] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:40:13,131] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:13,142] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.241 seconds
[2022-08-09 01:40:43,435] {processor.py:153} INFO - Started process (PID=467) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:43,438] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:40:43,440] {logging_mixin.py:115} INFO - [2022-08-09 01:40:43,440] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:43,658] {logging_mixin.py:115} INFO - [2022-08-09 01:40:43,656] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:40:43,660] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:40:43,670] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.241 seconds
[2022-08-09 01:41:14,034] {processor.py:153} INFO - Started process (PID=530) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:14,038] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:41:14,042] {logging_mixin.py:115} INFO - [2022-08-09 01:41:14,042] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:14,258] {logging_mixin.py:115} INFO - [2022-08-09 01:41:14,256] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:41:14,259] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:14,270] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.241 seconds
[2022-08-09 01:41:44,553] {processor.py:153} INFO - Started process (PID=593) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:44,555] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:41:44,557] {logging_mixin.py:115} INFO - [2022-08-09 01:41:44,556] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:44,797] {logging_mixin.py:115} INFO - [2022-08-09 01:41:44,794] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:41:44,798] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:41:44,810] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.262 seconds
[2022-08-09 01:42:15,200] {processor.py:153} INFO - Started process (PID=656) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:15,203] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:42:15,205] {logging_mixin.py:115} INFO - [2022-08-09 01:42:15,205] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:15,425] {logging_mixin.py:115} INFO - [2022-08-09 01:42:15,423] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:42:15,427] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:15,438] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.244 seconds
[2022-08-09 01:42:46,022] {processor.py:153} INFO - Started process (PID=719) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:46,025] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:42:46,028] {logging_mixin.py:115} INFO - [2022-08-09 01:42:46,027] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:46,247] {logging_mixin.py:115} INFO - [2022-08-09 01:42:46,245] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:42:46,249] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:42:46,259] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.244 seconds
[2022-08-09 01:43:17,014] {processor.py:153} INFO - Started process (PID=783) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:17,015] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:43:17,016] {logging_mixin.py:115} INFO - [2022-08-09 01:43:17,016] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:17,234] {logging_mixin.py:115} INFO - [2022-08-09 01:43:17,232] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:43:17,235] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:17,246] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.235 seconds
[2022-08-09 01:43:47,956] {processor.py:153} INFO - Started process (PID=838) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:47,958] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:43:47,959] {logging_mixin.py:115} INFO - [2022-08-09 01:43:47,959] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:48,207] {logging_mixin.py:115} INFO - [2022-08-09 01:43:48,205] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:43:48,209] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:43:48,220] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.266 seconds
[2022-08-09 01:44:18,952] {processor.py:153} INFO - Started process (PID=901) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:18,954] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:44:18,957] {logging_mixin.py:115} INFO - [2022-08-09 01:44:18,956] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:19,172] {logging_mixin.py:115} INFO - [2022-08-09 01:44:19,170] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:44:19,173] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:19,184] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.240 seconds
[2022-08-09 01:44:49,978] {processor.py:153} INFO - Started process (PID=965) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:49,980] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:44:49,982] {logging_mixin.py:115} INFO - [2022-08-09 01:44:49,982] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:50,203] {logging_mixin.py:115} INFO - [2022-08-09 01:44:50,200] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:44:50,204] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:44:50,214] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.242 seconds
[2022-08-09 01:45:20,883] {processor.py:153} INFO - Started process (PID=1028) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:20,887] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:45:20,890] {logging_mixin.py:115} INFO - [2022-08-09 01:45:20,890] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:21,121] {logging_mixin.py:115} INFO - [2022-08-09 01:45:21,118] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:45:21,123] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:21,135] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.257 seconds
[2022-08-09 01:45:51,292] {processor.py:153} INFO - Started process (PID=1093) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:51,294] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:45:51,294] {logging_mixin.py:115} INFO - [2022-08-09 01:45:51,294] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:51,508] {logging_mixin.py:115} INFO - [2022-08-09 01:45:51,506] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:45:51,509] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:45:51,522] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.232 seconds
[2022-08-09 01:46:22,214] {processor.py:153} INFO - Started process (PID=1155) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:22,217] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:46:22,220] {logging_mixin.py:115} INFO - [2022-08-09 01:46:22,220] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:22,455] {logging_mixin.py:115} INFO - [2022-08-09 01:46:22,453] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:46:22,456] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:22,468] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.259 seconds
[2022-08-09 01:46:52,880] {processor.py:153} INFO - Started process (PID=1219) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:52,883] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:46:52,884] {logging_mixin.py:115} INFO - [2022-08-09 01:46:52,884] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:53,111] {logging_mixin.py:115} INFO - [2022-08-09 01:46:53,108] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:46:53,112] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:46:53,124] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.248 seconds
[2022-08-09 01:47:23,745] {processor.py:153} INFO - Started process (PID=1283) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:23,746] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:47:23,747] {logging_mixin.py:115} INFO - [2022-08-09 01:47:23,747] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:23,986] {logging_mixin.py:115} INFO - [2022-08-09 01:47:23,984] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:47:23,987] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:23,997] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.255 seconds
[2022-08-09 01:47:54,601] {processor.py:153} INFO - Started process (PID=1337) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:54,604] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:47:54,606] {logging_mixin.py:115} INFO - [2022-08-09 01:47:54,606] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:54,832] {logging_mixin.py:115} INFO - [2022-08-09 01:47:54,830] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:47:54,835] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:47:54,846] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.251 seconds
[2022-08-09 01:48:25,459] {processor.py:153} INFO - Started process (PID=1400) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:25,460] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:48:25,461] {logging_mixin.py:115} INFO - [2022-08-09 01:48:25,461] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:25,690] {logging_mixin.py:115} INFO - [2022-08-09 01:48:25,687] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:48:25,692] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:25,706] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.249 seconds
[2022-08-09 01:48:56,346] {processor.py:153} INFO - Started process (PID=1463) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:56,348] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:48:56,349] {logging_mixin.py:115} INFO - [2022-08-09 01:48:56,349] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:56,588] {logging_mixin.py:115} INFO - [2022-08-09 01:48:56,586] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:48:56,589] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:48:56,604] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.260 seconds
[2022-08-09 01:49:27,237] {processor.py:153} INFO - Started process (PID=1526) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:27,240] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:49:27,243] {logging_mixin.py:115} INFO - [2022-08-09 01:49:27,243] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:27,478] {logging_mixin.py:115} INFO - [2022-08-09 01:49:27,475] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:49:27,481] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:27,493] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.261 seconds
[2022-08-09 01:49:58,209] {processor.py:153} INFO - Started process (PID=1589) to work on /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:58,212] {processor.py:641} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2022-08-09 01:49:58,214] {logging_mixin.py:115} INFO - [2022-08-09 01:49:58,214] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:58,454] {logging_mixin.py:115} INFO - [2022-08-09 01:49:58,452] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 52, in <module>
    endepoint='api/'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'endpoint'
[2022-08-09 01:49:58,455] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2022-08-09 01:49:58,467] {processor.py:161} INFO - Processing /opt/airflow/dags/user_processing.py took 0.264 seconds
